In [32]:
import pandas as pd

In [33]:
# read and analyse csv file
# check for null - none found
BCN_2016= pd.read_excel(".\datasets\BCN_2016.xlsx")
BCN_2016.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 3 columns):
Country    600 non-null object
Number     600 non-null object
Month      600 non-null object
dtypes: object(3)
memory usage: 14.1+ KB

In [34]:
BCN_2016

                            Country   Number     Month
0                        Alemanya    21369     January
1                         Àustria     2881     January
2                         Bèlgica     5932     January
3                        Bulgària      683     January
4                           Xipre      291     January
5                         Croàcia      438     January
6                       Dinamarca     2696     January
7                      Eslovàquia      531     January
8                       Eslovènia      406     January
9                         Estònia      278     January
10                      Finlàndia     2824     January
11                         França    37162     January
12                         Grècia     1644     January
13                        Hongria     1277     January
14                        Irlanda     5095     January
15                         Itàlia    31652     January
16                        Letònia      222     January
17                       Lituània      443     January
18                      Luxemburg      223     January
19                          Malta       99     January
20                  Països Baixos     8550     January
21                        Polònia     4337     January
22                       Portugal     5313     January
23                     Regne Unit    32935     January
24                Republica Checa     1124     January
25                        Romania     1179     January
26                         Suècia     4492     January
27             Resta Unió Europea     2208     January
28                       Islàndia      156     January
29                  Liechtenstein       86     January
..                              ...      ...       ...
570                 Països Baixos     8477    December
571                       Polònia     3672    December
572                      Portugal     7608    December
573                    Regne Unit    33549    December
574               Republica Checa      963    December
575                       Romania     2132    December
576                        Suècia     3820    December
577            Resta Unió Europea     2857    December
578                      Islàndia      234    December
579                 Liechtenstein      101    December
580                       Noruega     2801    December
581                        Rússia     7636    December
582                        Suïssa     8596    December
583                       Turquia     2197    December
584                       Ucraïna     1159    December
585                Resta d'Europa     7367    December
586                     Argentina     4042    December
587                        Brasil     5978    December
588                        Canada     3643    December
589                  Estats Units    29024    December
590                         Mèxic     2692    December
591              Resta d'Amèrica     11218    December
592                     Sudàfrica      856    December
593                Resta d'Àfrica    10521    December
594                          Japó    11539    December
595                          Xina     9833    December
596                 Corea Del Sud     3746    December
597                  Resta d'Àsia    20534    December
598                     Austràlia     3199    December
599                 Resta del món    20482    December

[600 rows x 3 columns]

#### changing number of visitors to float

In [35]:
BCN_2016 = BCN_2016.astype({"Number": float})

In [36]:
BCN_2016.head()
BCN_2016.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 3 columns):
Country    600 non-null object
Number     600 non-null float64
Month      600 non-null object
dtypes: float64(1), object(2)
memory usage: 14.1+ KB

In [37]:
BCN_2016.to_csv("BCN_2016_CLEAN.csv")

## import to database

In [38]:
from sqlalchemy import create_engine
import pymysql

In [39]:
driver = "mysql+pymysql"
user = "root"
password = "Ir0nhack"
ip = "35.192.169.188"
database = "Project_2"

In [40]:
connection_string = f"{driver}://{user}:{password}@{ip}/{database}"

In [41]:
engine = create_engine(connection_string)

In [42]:
BCN_2016.to_sql("BCN_2016", engine)